### PR TITLE
Updating info messages

### PR DESCRIPTION
**Pull request by teh3vil**
Tested this a lot more than the last time, updated to latest versions
before push. Should be rosy!

Having some issues with Tox, can't get it installed on my crappy laptop. Hoping to get these amendments sorted in as few commits as possible, sorry for the mess.

edit: YAY! Only took 8 commits /noob

### CODE REVIEW

**Comment by teh3vil** [comment]
Anyone have a suggestion regarding: "Imports are incorrectly sorted." on Travis/Tox?

Can't seem to get tox to run on my craptop

**Comment by infinitewarp** [comment]
Not bad! I like the idea of having categorized [TAG] messages. I spotted a few inconsistencies, though, that I'll point out with inline comments shortly.

Since this changes a lot of the "feel" of the CLI, I'll leave it @j-e-k to provide additional feedback and decide on the merge.

**Comment by infinitewarp** [comment]
Actually, too many to bother replying inline, and it seems like *all* of the [INVENTORY] and [ENCOUNTER] messages are missing the proceeding tab character. Any reason for this pattern?

Personally, I'd rather simply have a single space (maybe the minus as an additional delimeter) following the [TAG]s instead of tab/notab. That would make it a bit easier to programmatically sift through the logs with your typical shell tools (`grep`, `cut`, `awk`, etc.).

**Comment by teh3vil** [comment]
Yeah. in the console they already take up as much space as the others when a tab is added, so i removed the tab on these to ensure they line up in the console. It's more for visual aesthetic, so that all log messages are aligned. I've only tested this on Windows though, but a friend has run it on his mac and it looked neat there too.

I realise the feeling of the bot changes quite a lot with this, and really would welcome any input for the message text from you guys.

**Comment by stolencatkarma** [comment]
I love the style you put into this! 
it does create longer lines of code. maybe we could reduce the frontend spam from self.log.info()

**Comment by sontek** [comment]
This has merge conflicts that need resolved.

**Comment by teh3vil** [comment]
Going to close this as it's becoming slowly outdated. I might try to come up with an easier way to do this that might be more beneficial, such as adding a translations.txt option or something. Probably will wait until after the pgoapi dependency change/total rebuild goes through

**Pull request closed without merging**
