### PR TITLE
use tox, flake8, and isort and clean up code violations

### PR DESCRIPTION
**Pull request by infinitewarp**
I've added [tox](https://tox.readthedocs.io/) and the appropriate configs for it, [flake8](http://flake8.pycqa.org/), and [isort](https://github.com/timothycrosley/isort) to lint check the code and report back on violations of standard Python coding convention.

I also did the janitorial duties of cleaning up the mountain of violations in the current code base (minus the generated POGOProtos module) so the checks would start passing immediately. If you're using any continuous integration tools, you should totally hook them up with tox.

If you accept this pull request, I'll submit another with an update to the README to explain how and when to use tox.

### CODE REVIEW

**Comment by sftwninja** [comment]
That is so clean, I could eat off of it. :+1:

**Comment by joychugh** [comment]
Hi ! thanks for pull request! I had to merge some existing ones that came before this one so you will have to merge some changes once its done, we can approve this.

**Comment by infinitewarp** [comment]
Great! I just merged and spruced things up again. Have a look and let me know what you think.

**Comment by infinitewarp** [comment]
Or not… looks like develop is so active I missed a recent commit. Just a moment!

**Comment by infinitewarp** [comment]
One more time! Should be OK or now. :)

**Comment by infinitewarp** [comment]
Sorry for all the back and forth, but actually please hold on merging this. I'm encountering some odd bugs on my branch that I think may be related to all the various merges.

**Comment by infinitewarp** [comment]
I'm going to have to stop fixing all these merge errors at some point… it's growing exhausting. Any chance you could pause merging for a few minutes until I can get one clean?

**Comment by infinitewarp** [comment]
I'm taking a break. Please let me know @j-e-k  when you're not actively merging other PRs. I can't keep fighting the incoming commits because each one is breaking things over and over until I can get one good flake8-cleaned commit out there.

**Comment by infinitewarp** [comment]
OK, it looks like things are back in good shape again. I've been running `pokecli.py` and `web.py` for a few minutes now, and everything appears to be in working order.

*Please* consider merging this PR before you start landing more commits on the develop branch. If I have to fight another round of merge conflicts, I may have to throw in the towel. 😰

**Comment by j-e-k** [comment]
Thank you for your work!

**Pull request merged**
