### PR TITLE
Added ability to transfer pokemons from the web interface.

### PR DESCRIPTION
**Pull request by Myhorta**
This is but a demonstration of interaction between the web interface and the bot. I didn't add more features because it would require a considerable work, and I don't know if you prefer to follow another way to allow on-the-fly interaction.

### CODE REVIEW

**Comment by j-e-k** [comment]
I love you. I will take at this now.

**Comment by Myhorta** [comment]
Just learned that a zerorpc doesn't support ipc:// in windows. I'll make some changes in order to accommodate that and commit once ready.

**Comment by j-e-k** [comment]
Was just asking in slack if anyone had windows to test it out with. You're a step ahead of me 😄

**Comment by joychugh** [comment]
awesome!

**Comment by Myhorta** [comment]
Should work now. Still needs to be tested both on windows and mac, platforms I don't own.

**Pull request merged**
