### PR TITLE
Added basic web server configuration (hostname/ports)

### PR DESCRIPTION
**Pull request by archeious**
Added the ability to do basic web server configuration.  e.g., set bound hostname or ip address and TCP port.

### CODE REVIEW

**Comment by destiny117** [comment]
nice, then i don't need to set the port manually after each merge :) however you should probably rename web_config.json to web_config.json.example and add web_config.json to .gitignore

**Comment by sftwninja** [comment]
@archeious if you do end up going with @destiny117's suggestion, would you mind changing the argument defaults to sensible defaults like `debug` is? Something like `127.0.0.1` and `5000` seem safe and least astonishing considering the current README.

**Comment by beeedy** [comment]
Agreed that defaults should, when possible, cause it so new features don't change a system

**Comment by archeious** [comment]
@destiny117 Done and Done
@beeedy  Yo dawg, I heard you like defaults to your defaults so I set the defaults to the previous defaults so existing systems will not be affected by this change.

**Pull request closed without merging**
