### PR TITLE
added color logs

### PR DESCRIPTION
**Pull request by rirze**
This is a WIP, currently using the `colorlog` package to color log messages. Colors are assigned per module, and the assignment is at this moment:

- `fort_walker`: blue
- `poke_catcher`: green
- `release`: yellow
- `evolve`: cyan

I will continue to add colors to other modules and will shift around color assignments, experimenting with best visibility. Let me know your suggestions (ideas for color assignments would help a bunch).

### CODE REVIEW

**Comment by skydrome** [comment]
the dark blue on [fort_walker] and the light blue on [poketrainer] are hard to tell apart

**Comment by BHGaming** [comment]
This looks really nice.  I adjusted the colors a bit (the blue was too dark to read sometimes).  My current setup is:

- Fort Walker: Cyan
- Poke Catch: Green
- Release: Yellow
- Evolve: Green

I also tried setting the Inventory text to Purple, and it worked, but it was showing each message 6 times.

**Comment by stolencatkarma** [comment]
can we have this as a config option? other then that i want to merge.

**Comment by rirze** [comment]
@stolencatkarma there are still standard logging statements I need to cleanup, and also as @BHGaming  mentioned, the inventory log prints multiple times, which is odd and something I need to look into. I'll implement config options as well. Important thing to note is that there are only certain colors, which I'll add into the config README:

The following escape codes are made available for use in the format string:

- `{color}`, `fg_{color}`, `bg_{color}`: Foreground and background colors.
- `bold`, `bold_{color}`, `fg_bold_{color}`, `bg_bold_{color}`: Bold/bright colors.
- `reset`: Clear all formatting (both foreground and background colors).

The availible color names are `black`, `red`, `green`, `yellow`, `blue`,
`purple`, `cyan` and `white`. Multiple escape codes can be used at once by
joining them with commas. (ex. `"black,bg_white"`)

**Comment by rirze** [comment]
As far as I can tell, this is good to go

**Comment by j-e-k** [comment]
Can you rebase one last time so I can merge this in? Thanks!

**Comment by rirze** [comment]
@stolencatkarma @j-e-k So with these new config changes, do I add color configs into the example or not (they go under console, which seems to be too 'advanced' for first-time users)

**Pull request merged**
