### PR TITLE
uses the pokeball with 100 % chance of a catch.

### PR DESCRIPTION
**Pull request by stolencatkarma**
this makes other pokeballs besides basic get thrown a lot. It tries to use the pokeball with 100% chance of catching the pokemon first try

reccommend turning on berries too.

### CODE REVIEW

**Comment by rirze** [comment]
...This should not be default behavior. What your code is doing is basically choosing the best ball everytime unless capture probability is 100% (in which case only the pokeball will be chosen). I'm currently writing a pull request that where you can choose the 'capture probability threshold' and set it in the config (i.e. you can set the rate to be 15% or 100% like you did here).

**Comment by joshpalan** [comment]
@rirze I already have this in a pull request #335

**Comment by rirze** [comment]
@joshpalan ah my bad, I didn't see that pull request. Hope it gets merged soon

**Comment by stolencatkarma** [comment]
yours is a much better solution. i'll close this.

**Pull request closed without merging**
