### PR TITLE
Allow bot to stop catching pokemon and farm balls when inventory is depleted

### PR DESCRIPTION
**Pull request by sftwninja**
I found it kinda annoying to switch the bot in-between collecting and catching. This was my solution.

Flags:
`ENABLE` : `Boolean`, whether or not this feature is enabled
`POKEBALL_FARM_THRESHOLD` : `Integer`, when the observed pokeball count drops on or below this number, skip catching pokemon and begin collecting.
`POKEBALL_CONTINUE_THRESHOLD`: `Integer`, when the observed pokeball count reaches this amount, stop farming and go back to catching pokemon.
`FARM_IGNORE_POKEBALL_COUNT`: `Boolean`, Whether to include this ball in counting. Same goes for `GREATBALL`, `ULTRABALL`, and `MASTERBALL`. Masterball is ignored by default.
`FARM_OVERRIDE_STEP_SIZE`: `Integer`, When it goes into farming mode, the bot assumes this step size to potentially speed up resource gathering. _This might lead to softbans, I'm not savvy with what causes issues._, but it works for me. Setting to `-1` disables this feature. Disabled by default for safety.

### CODE REVIEW

**Comment by j-e-k** [comment]
Please update the README.md with documentation (what you have in the PR) 😄 
Thanks for the contribution!

**Comment by sftwninja** [comment]
Updated with info. Thanks :)

**Comment by destiny117** [comment]
looks good to me

**Comment by j-e-k** [comment]
Great, thanks for the PR!

**Pull request merged**
