### PR TITLE
Ability to automatically use lucky eggs

### PR DESCRIPTION
**Pull request by xezero**
If specified in the config file, we can now have the bot automatically use lucky eggs every 30 minutes to double the XP :)

### CODE REVIEW

**Comment by beeedy** [comment]
just FYI you want to pull into development branch and not master! Might be worth while to build upon this and have the bot hold onto X number of pokemon to save for use with a lucky egg... hmmmmm

**Comment by j-e-k** [comment]
Please open a PR for this into develop instead of master. Thanks!

**Comment by xezero** [comment]
New PR :)

**Comment by joychugh** [comment]
@beeedy we can't hold enough to justify lucky egg, since we evolve pretty fast (Being a bot) but surely lucky egg is useful to use normally to deploy the bot in crowded area and let it rip

**Pull request closed without merging**
