### PR TITLE
Fix issue #170

### PR DESCRIPTION
**Pull request by destiny117**
hopefully fixes the crash

### CODE REVIEW

**Comment by sontek** [comment]
Oops, didn't realize you sent this PR.... Check out https://github.com/j-e-k/poketrainer/pull/176 as an alternative fix

**Comment by sontek** [comment]
@destiny117 Can you rebase this to get rid of all the extra commits?

**Comment by j-e-k** [comment]
Just merged in #175 from @sontek , I don't think this is needed any more, confirm?

**Comment by destiny117** [comment]
yes, it's obsolete now

**Pull request closed without merging**
