### PR TITLE
sleep time changes to make it more effecient/crash less.

### PR DESCRIPTION
**Pull request by stolencatkarma**

### CODE REVIEW

**Comment by DannyiCracked** [comment]
Running locally -- seems to work fine. Much faster.

**Comment by infinitewarp** [comment]
It may be faster, but I thought the sleeps were deliberate to keep from hitting the rate-limiting wall and to simulate a more realistic walking/collecting behavior. Did you consider those points with this change?

**Comment by stolencatkarma** [comment]
the sleeps were put in to specifically address the rate limiting. it fixes all those errors and speeds it up by about 3x. you can change step size to slow it back down but as of now this won't cause any softban issues.

**Comment by j-e-k** [comment]
I feel like we might want to add a config option to allow people to specify a multiplier to slow down the bot more if they want to for some reason...what do you think?

**Comment by j-e-k** [comment]
Other than that though I will run it when I get home then get it merged in!

**Comment by stolencatkarma** [comment]
you could make a config and replace all the gevent.sleep(0.2) with the config. that's the time it waits before most RPC calls. it's 1 second on getting map objects.

**Comment by xezero** [comment]
This is fantastic! :)

**Comment by j-e-k** [comment]
Okie dokie will merge this in, if people have complaints post them in an issue and mention @stolencatkarma so he can see what's up

**Pull request merged**
