### PR TITLE
Merge master to develop

### PR DESCRIPTION
**Pull request by infinitewarp**
Trying a merge instead of a rebase since https://github.com/j-e-k/poketrainer/pull/320 has conflicts.

### CODE REVIEW

**Comment by infinitewarp** [comment]
Don't merge yet… Travis is complaining about some of this change.

**Comment by infinitewarp** [comment]
OK, Travis looks to be happy again! 🎉

**Comment by j-e-k** [comment]
Looks good to me, any other contributors have any thoughts?

**Comment by j-e-k** [comment]
Let's do this 🎉

**Pull request merged**
