### PR TITLE
Multi-Locations

### PR DESCRIPTION
**Pull request by teh3vil**
Walks to each location in the list whenever "walk to origin" is called.
Takes co-ordinates or addresses. Can be used to guide the bot across a
wider area while keeping "Stay within proximity" low. This is useful
when trying to hit up multiple "good" spots in one run, or hatch eggs by
walking very far between locations before commencing usual botting
behaviours (like hitting every pokestop in an area)

Added get_position_address function (ripped off from pokecli.py) to geocode a location into an address for pretty output within the bot interface (a later commit might take advantage of this)

### CODE REVIEW

**Comment by stolencatkarma** [comment]
looks good to me.

**Comment by j-e-k** [comment]
Can you add a note to the readme? Once that is in we can get this merged. Thanks! 🎉

**Comment by teh3vil** [comment]
Will do!

**Comment by j-e-k** [comment]
Can you please rebase? Thanks!

**Comment by teh3vil** [comment]
Going to close this and re-open it with rebased code. Not even sure if the method I was using will work the same anymore, as the "walk_to_origin" system after rebase has totally changed.

**Pull request closed without merging**
