### PR TITLE
Complete Refactor

### PR DESCRIPTION
**Pull request by destiny117**
This is my attempt at completely refactoring poketrainer to make it cleaner and easier to develop
What i've done so far:
- [x] completely seperated pgoapi, similar to #437 
- [x] created a `library` directory with pgoapi and a libencrypt skeleton
- [x] created a `helper` directory with static helper functions
- [x] moved web stuff to `web` directory
- [x] moved resources to seperate `resources` folder
- [x] created directory `poketrainer` holding the bot itself
- [x] put all bot functionality inside seperate classes in `poketrainer` dir
- [x] moved `Listener.py` functionality directly to `poketrainer/poketrainer.py`
- [x] refactored walking / spinning, now every heartbeat is moving at maximum step_size, makes it easier to predict how fast step_size will actually be
- [x] added start / stop functionality to `poketrainer/poketrainer.py`, creating his own pseudo-thread with exception handling / restarting
- [x] added configuration loading / reloading to `poketrainer/poketrainer.py` instead of ´pokecli.py´
- [x] alot of other small stuff
- [x] because the heartbeat is now more or less every 1 second, it is now limited to every 3rd loop via variable `self._heartbeat_frequency` within `poketrainer.py`. this might need some documentation and a config variable if ppl are not happy with this.

Still to do:
- [x] rebase
- [x] fix fort-caching from rebase
- [x] change sleeps to work well with default values
- [x] cleanup imports / other tox corrections

Maybe after the merge?
- [x] change docker accordingly
- [x] testing with different config setups
- [ ] further refactoring of some static functions, removing some unneeded functions

It would be nice if you can check the code and give some feedback.
The branch is in a working state, so you can also to test it out with your config [direct link to branch](https://github.com/destiny117/poketrainer/tree/refactor)

Furthermore it would be nice if we don't merge too many PR until (if) this is being merged.

### CODE REVIEW

**Comment by j-e-k** [comment]
oh boy what a long time coming this has been. Thanks for your work!

**Comment by xthedeus** [comment]
Nice work! 😄

**Comment by rirze** [comment]
Similiar to what I did in #437, could you separate the api completely from the project and have it as a dependency instead? Something like this in the `requirements.txt` would do fine:
`-e git+git://github.com/keyphact/pgoapi.git#egg=pgoapi`

**Comment by destiny117** [comment]
@rirze this sounds cool, but i can see different reason not to do that:
- there are already small changes to the pgoapi for our bot
- automatic installation of new versions might break stuff and create unneeded pull-requests
- keyphact's repo might go down

what do others think about that?

**Comment by j-e-k** [comment]
I guess one option is that we maintain our own fork of pgoapi and link to
that?

**Comment by destiny117** [comment]
Maintaining our own fork is definitly an option :) idk either if we decide to pull it from someone elses repository, but i also don't see a problem with just leaving it inside

I have now rebased and fixed everything i encountered. If we have a stable branch i would be ok with merging this, so we have some actual feedback

**Comment by stolencatkarma** [comment]
I'm going to spend a few hours running this and testing setups.

**Pull request merged**
