### PR TITLE
Duplicate transfer round: 2

### PR DESCRIPTION
**Pull request by beeedy**
I am not sure what is blocking the auto-merge but this should be the completed branch that allows for the release of duplicate pokemon! 

As mentioned before this is a feature that is disabled by default and should be carefully configured to avoid unwanted loss of pokemon. This introduces a couple new concepts including that of a pokemon's LVL which is a configurable value comprised of CP and IV. At its core this feature allows for you to specify how the system should compare two pokemon in regards to CP and IV using their new LVL and also remove *all duplicates. The new config "RELEASE_DUPLICATES_SCALER" is a value multiplied by the highest lvl pokemon of a type's lvl. The bot will only transfer pokemon with a lvl that is less than this product. This in essence allows a user to keep pokemon that are close together in lvl so that they can manually decide which to transfer. To disable this, set RELEASE_DUPLICATES_SCALER to 1.0

"all" comes with some stipulations. It will still abide by the configuration "MIN_SIMILAR_POKEMON" and also will not release pokemon above the LVL limit specified by RELEASE_DUPLICATES_MAX_LV. Pokemon also flagged as favorites or in the list of pokemon to keep will not be transferred. 

NOTE: THIS IS IMPORTANT!!! DO NOT IGNORE THIS!!!!! WHEN YOU ENABLE THE TRANSFER OF DUPLICATES, YOU ARE ALSO DISABLING THE CONFIGS "KEEP_IV_OVER" AND "KEEP_CP_OVER".

### CODE REVIEW

**Comment by xezero** [comment]
Great concept! The only issue I see with this is we would lose the ability to keep high CP **OR** high IV pokemon, since LVL has to be derived from the combination of the two - in a lot of cases we would want to choose between both.

For instance, sometimes we'd want to choose a 2000 CP Snorlax with only 30% IV over a 500 CP that is 95% IV considering the rarity of getting Snorlax candies to power it up, but other times we'd want to transfer a 2000 CP Arcanine that is 30% IV in favor of a 500 CP that is 95% IV since we'd be able to boost it up very easily with Growlith candies.

Hope I'm making sense!

**Comment by Clintoxen** [comment]
@xezero couldn't we just set the cp or iv value in this PR to zero if we only want it to go by CP or IV?

**Comment by Clintoxen** [comment]
self.DEFINE_POKEMON_LV = config.get("DEFINE_POKEMON_LV", "CP") # define a pokemon's lvl, options are CP, IV, CP*IV, CP+IV 

Actually Looks like you can choose either or in the code. Sorry on mobile so can't edit my last comment

**Comment by xezero** [comment]
@Clintoxen  I might need to clarify. What I mean is the algorithm can't choose to select a criteria based on CP or IV separately **WHILE** running. Indeed you can choose either or in the configuration, but you can't do something like LVL="CP|IV" where | is **or**.

**Comment by Clintoxen** [comment]
Gotcha

**Comment by beeedy** [comment]
@xezero personally I see no benefit to a system of using an **or** operator, in fact it seems like a great method for rapidly filling up your backpack with low CP but high IV pokemon. I want to note that you can simply disable this method in the config and it will fall back onto the originial method of transferring pokemon which can be used as an **or** type of system.

**Comment by COLDPOKEMONGO** [comment]
Sorry, I'd like to ask here what does "keep_iv_min_percent_cp" correspond to and what values can you put in?

Also, for some reason pokemon with high iv but a lower cp seems to be getting removed for me.. I am pasting the relevant sections below:
"KEEP_CP_OVER": 1000,
 "KEEP_IV_OVER": 90,
 "KEEP_IV_MIN_PERCENT_CP": 0, 

and i just toggled 
"MIN_SIMILAR_POKEMON": 0

Before this, min_similar_pokemon was at 1.

**Comment by beeedy** [comment]
@COLDPOKEMONGO those settings are completely irrelevant to this PR, and consequently, the true lack of control those settings give you was part of the inspiration behind this method. MIN_SIMILAR_POKEMON set to zero means the system will remove a pokemon that doesn't meet specs, even if it is the only type of that pokemon you own. The logic behind how the other configs are used seems kinda flaky but from my understanding it will keep any pokemon that has a cp larger than KEEP_CP_OVER OR a pokemon that has a iv larger than KEEP_IV_OVER. the last config is a little funky and I *believe* it keeps pokemon that are within KEEP_IV_MIN_PERCENT percent of your IV floor. If you are looking to just remove duplicate pokemon I suggest switching to the method proposed in this PR as I personally believe it is more predictable and configurable. Hope that helps!

**Comment by j-e-k** [comment]
Can you add some info to the README.md so I can merge this in?

Thanks again for putting this together 🎉

**Comment by COLDPOKEMONGO** [comment]
@beeedy Thank you! I was in the midst of trying this proposed method :+1:  

Thanks for your contribution!

**Comment by beeedy** [comment]
Ahh completely forgot about the readme, will do that now

**Comment by beeedy** [comment]
Readme updated

**Comment by j-e-k** [comment]
Okie dokie, merging. Thanks for the contribution!

**Comment by j-e-k** [comment]
Handled the conflicts, please make sure everything is still working as you intended in develop. In the future please make sure you keep your branch rebased 😄 
Thanks!

**Comment by beeedy** [comment]
Will check it this evening! Seems develop changes so frequently as soon as I rebase I am already 5 merges behind  :smile:

**Comment by j-e-k** [comment]
I don't even know what all of the features are in this bot anymore 😨

**Comment by beeedy** [comment]
I know what you mean, when rebasing I couldn't get the bot to work and then found out it was because of all the new features :yum: It might be time to seriously consider braking the bot into smaller modules to better keep track of and organize features

**Comment by joychugh** [comment]
Thank you for this! I love it! I just encapsulated the mechanism in one method to make it cleaner in develop branch. please have a look @beeedy let me know if anything weird pops up.

**Comment by xezero** [comment]
@beeedy Well the only reason I myself need the OR mechanism is that now that I'm level 31 and pretty much only doing gym battles, it is practically crucial for me to get either high CPs (for the rarer pokemons) OR high IVs (for the more common pokemons in which I have tons of candy to pump up).

Your RELEASE_DUPLICATES feature is awesome though for very long stretches of XP farming without worry about the box filling up, so thanks for it! :)

**Comment by COLDPOKEMONGO** [comment]
@xezero I can't help but ask what is the config you are using as mine seems to always keep the higher CP pokemon despite setting a Keep Min IV of 90%.

**Comment by xezero** [comment]
@COLDPOKEMONGO It's currently:
```
"KEEP_IV_OVER": 90,
"KEEP_CP_OVER": 1000
```

The master branch is still using MIN_KEEP_IV instead of KEEP_IV_OVER (develop branch only currently).

**Comment by COLDPOKEMONGO** [comment]
@xezero how about "KEEP_IV_MIN_PERCENT_CP"?
I have the same config as but this happens for example:

> 220 cp with 40% IV 
120 cp with 90% IV

where the 220cp pokemon gets kept over the 120cp pokemon despite 

> "KEEP_IV_OVER": 90,
"KEEP_CP_OVER": 1000

**Comment by xezero** [comment]
Hm, well I don't see KEEP_IV_MIN_PERCENT_CP anywhere, are you on the latest develop build (commit 390c9c802040aa6ec39577c8a3f449609bf4492a)?

**Comment by COLDPOKEMONGO** [comment]
@xezero that was a previous build, so yea I'm gonna test it out on the current one and get back on that.

**Comment by beeedy** [comment]
MIN_SIMILAR_POKEMON means that the bot will always keep X number of that pokemon (defaults to one, so the bot will never transfer the last of a specific type)

**Comment by xezero** [comment]
For reference sake, fixed a minor issue related to this in #171

**Pull request merged**
