### PR TITLE
Configurable web server options

### PR DESCRIPTION
**Pull request by archeious**

### CODE REVIEW

**Comment by infinitewarp** [comment]
Don't forget to run `tox`. I still see a few things that should cause it to complain. :)

**Comment by archeious** [comment]
Tox will not run on my box.  Looks like it is trying to setup some sort of virtual env which will not work with my setup.  If there is a coding standard out there point me at it and I will follow it.

**Comment by infinitewarp** [comment]
https://www.python.org/dev/peps/pep-0008/

**Comment by destiny117** [comment]
still PR had quite some conflicts / errors, but i merged manually now and the feature is available

**Pull request closed without merging**
