### PR TITLE
Web interface in php

### PR DESCRIPTION
**Pull request by RikudouSage**
I started making a web ui in php, it also includes a shell script to start the webserver.

For now it can only do settings, in next update I would also show the stats etc. from dump files.

### CODE REVIEW

**Comment by mdjong1** [comment]
I'd recommend replacing é with `&eacute;` in the html file to avoid it being misdisplayed

**Comment by destiny117** [comment]
while i appreciate the effort you put into this, it adds redundancy for config options

just to make it clear, this will require someone to continually keep the web interface updated with the core config for it to work

**Comment by j-e-k** [comment]
Expanding on what @destiny117  said,  I am concerned about introducing PHP as a dependency. If you want to work on this further I suggest you maintain it as a fork and I can provide a link from the readme.

**Comment by RikudouSage** [comment]
I don't think the php would be so big problém, on most systems it takes one command to install. And I would update the web gui to work with core features.

**Pull request closed without merging**
